services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goexpert
      MYSQL_PASSWORD: ''
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql
